# docker-compose.yml
version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - '5000:5000'
    environment:
      - DB_URL=mongodb://mongo:27017/socialDB
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
    ports:
      - '3000:3000'
    depends_on:
      - backend
    environment:
      - BASE_URL_API=http://backend:5000
  mongo:
    image: mongo:4.4
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
